services:

  Dosmi.Sections.domain.SectionRepository:
    class: ../../../../../Contexts/Dosmi/Sections/infrastructure/persistence/mongo/MongoSectionRepository
    arguments: [ "@Dosmi.MongooseConnection" ]

  Dosmi.Sections.application.SectionSearcher:
    class: ../../../../../Contexts/Dosmi/Sections/application/search/SectionSearcher
    arguments: [ "@Dosmi.Sections.domain.SectionRepository" ]


