services:

  Dosmi.Preachers.domain.PreacherRepository:
    class: ../../../../../Contexts/Dosmi/Preachers/infrastructure/persistence/mongo/MongoPreacherRepository
    arguments: [ "@Dosmi.MongooseConnection" ]

  Dosmi.Preachers.application.PreacherCreator:
    class: ../../../../../Contexts/Dosmi/Preachers/application/create/PreacherCreator
    arguments: [ "@Dosmi.Preachers.domain.PreacherRepository" ]

