services:

  Apps.dosmi.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []

  Apps.dosmi.controllers.PreachersPutController:
    class: ../../controllers/PreachersPutController
    arguments: ['@Dosmi.Preachers.application.PreacherCreator']

  Apps.dosmi.controllers.SectionsGetController:
    class: ../../controllers/SectionsGetController
    arguments: ['@Dosmi.Sections.application.SectionsSearcher']



