services:

  Apps.dosmi.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []

  Apps.dosmi.controllers.PublishersPutController:
    class: ../../controllers/PublishersPutController
    arguments: ['@Dosmi.Publishers.application.PublisherCreator']

  Apps.dosmi.controllers.SectionsGetController:
    class: ../../controllers/SectionsGetController
    arguments: ['@Dosmi.Sections.application.SectionsSearcher']



