imports:
  - { resource: ./application.yaml }

services:
  Dosmi.EnvironmentArranger:
    class: ../../../../../tests/Contexts/Shared/infrastructure/mongo/MongooseEnvironmentArranger
    arguments: ['@Dosmi.MongooseConnection']

