imports:
  - { resource: ./application.yaml }

services:
  Dosmi.EnvironmentArranger:
    class: ../../../../../tests/Contexts/Shared/infrastructure/mongo/MongoEnvironmentArranger
    arguments: ['@Dosmi.MongoClient']
